# Generated by Django 5.0.2 on 2024-02-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excursion',
            options={'verbose_name': 'Экскурсия', 'verbose_name_plural': 'Экскурсии'},
        ),
        migrations.AddField(
            model_name='excursion',
            name='pict',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='pictures', verbose_name='Фото'),
        ),
    ]
